### ISSUE TITLE
Policy Server creation page

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/ui#25]

**Comment by jordojordo** [comment]
It would be nice to have a better structured creation page for policy servers. Currently it lacks some useful inputs and is very plain:

![policy-server-create](https://user-images.githubusercontent.com/40806497/161272900-1bc663fc-068e-4b9b-b356-2e65a1f2f58a.png)


---
Some inputs to include
- [ ] name
- [ ] namespace
- [ ] image
  - [ ] version if using default `policy-server` 
- [ ] annotations
- [ ] labels
- [ ] replicas
- [ ] serviceAccountName
- [ ] verificationConfig
  - Needs to be able to "Read from File" as the [config can be quite long](https://github.com/kubewarden/policy-server/blob/main/verification.yml.example)
- [ ] insecureSources
- [ ] sourceAuthorities ([example](https://github.com/kubewarden/policy-server/blob/d24d823d59e10a32ff68ccb3362151685c9dc40f/sources.yml.example#L5))

**Comment by jordojordo** [comment]
[Reference](https://github.com/rancher/dashboard/commit/cb048a55881975aeda1ea77974dd13a37abaca42)

You are now able to create Policy Servers with a more guided approach to the configuration. 

https://user-images.githubusercontent.com/40806497/161860796-44cc475f-9655-4158-b296-2a3b61745aa7.mp4

_Note:_ In the interest of time, the `sourceAuthorities` input will just be an yaml editor which allows you to either specify a file endpoint or you can paste in your certificate.
