### ISSUE TITLE
Allowed Proc Mount Types PSP: wrong default

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#292]
### Current Behavior

Policy docs says: `allow_unmasked_proc_mount_type is false by default`.
UI default value for allow_unmasked_proc_mount_type is true.

### Expected Behavior

`Settings -> Allow Unmasked Proc Mount Type` should not be selected by default.

**Comment by jvanz** [comment]
@jordojordo, as far as  I can see, we can close this issue, right?

**Comment by kravciak** [comment]
Fixed in v0.1.6
