### ISSUE TITLE
Fix bugs found in policy settings in UI

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#294]
- [x] Custom Policy
- [x] Allow Privilege Escalation PSP
- [x] Allowed Fs Groups PSP
 - selecting RunAsAny does not remove ranges
- [x] Allowed Proc Mount Types PSP
 - https://github.com/kubewarden/ui/issues/292
- [x] Apparmor PSP
- [x] Capabilities PSP
- [x] -Disallow Service Loadbalancer
- [x] -Disallow Service Nodeport
- [x] -Environment Variable Secrets Scanner
- [x] Flexvolume Drivers Psp
 - https://github.com/kubewarden/ui/issues/293
- [x] Ingress Policy
 - ~~`If allowPorts and denyPorts are provided together denyPorts is prioritized` - I should define only one of them~~
- [x] -Pod Privileged Policy
- [x] -Readonly Root Filesystem PSP
- [x] Safe Annotations
 - https://github.com/kubewarden/ui/issues/295
 - https://github.com/kubewarden/ui/issues/300
- [x] Safe Labels
- [x] Seccomp PSP
- [x] Sysctl PSP
- [x] Trusted Repos
 - https://github.com/kubewarden/ui/issues/301
- [x] Volumes PSP
- [x] Hostpaths PSP
- [x] User Group PSP
 - https://github.com/kubewarden/ui/issues/297
 - https://github.com/kubewarden/ui/issues/296
- [x] Verify Image Signatures
 - https://github.com/kubewarden/ui/issues/299
 - I should be able to add multiple `signatures` since it's a list - [README](https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures#settings)
 - settings are not cleared when I change signature type
- [x] volumeMounts
- [x] Host Namespaces PSP
- [x] Selinux PSP
 - https://github.com/kubewarden/ui/issues/298
- [x] Environment Variable Policy
- [x] Deprecated API Versions
- [x] Pod Runtime

**Comment by flavio** [comment]
Waiting for @kravciak to verify the fixes

**Comment by kravciak** [comment]
Closing, there are only couple cards left - no need to track them here.
