### ISSUE TITLE
User Group PSP: `overwrite` option is available for `MustRunAsNonRoot` setting

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#297]
### Current Behavior

From [README](https://artifacthub.io/packages/kubewarden/user-group-psp/user-group-psp): `overwrite attribute can be set true only with the rule MustRunAs`

Currrently `overwrite` option is also available for `MustRunAsNonRoot`

**Comment by kravciak** [comment]
Now I always see overwrite option, does not depend on which rule I select.

![Screenshot from 2023-03-17 10-41-06](https://user-images.githubusercontent.com/538604/225868946-d7ea6ef6-2e6c-4d5d-9104-6f65771c5f0e.png)

**Comment by jordojordo** [comment]
This appears to be fixed with the latest user-group-psp-policy release:

![settings](https://user-images.githubusercontent.com/40806497/226605223-6bf7d68f-cbf5-400e-ab21-8aa0c3fe9965.png)

**Comment by flavio** [comment]
moved back to "TODO", @kravciak is on vacation this week.

**Comment by kravciak** [comment]
I can still create policy with unwanted overwrite value. If I enable overwrite and change the rule, setting is kept in yaml.

Error from policy server log:
```
ERROR policy_server: [clusterwide-zzz] settings are not valid: Some("Cannot set overwrite field with \"RunAsAny\"")
```

[Screencast from 2023-03-27 19-13-03.webm](https://user-images.githubusercontent.com/538604/228016679-3076ed3f-8e40-4524-b955-bc488be5754e.webm)
