### ISSUE TITLE
Verify Image Signatures: Certificate settings hide when I try to add annotation

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#299]
### Current Behavior

Certificate settings hide when I click `Add` annotation button

To reproduce:
- open `Verify Image Signatures -> Settings`
- select `Certificate` signature type
- click `Add` certificates
- click `Add` annotations

[Screencast from 2023-03-09 14-21-05.webm](https://user-images.githubusercontent.com/538604/224036691-39a28709-afee-40dc-9e61-5d3977bfde62.webm)

**Comment by kravciak** [comment]
I don't see this issue when I user extension from loaded by `yarn dev`, I would keep the issue around until the next  release co confirm it's fixed in production or just not visible in dev.

**Comment by jordojordo** [comment]
I could not replicate this either. Both with `yarn dev` and by loading the [latest rc](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.5-rc2) `1.0.5-rc2`. Closing as this seems to be fixed.
