### ISSUE TITLE
Cancelling edit returns to overview not detail page

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PolicyServers -> Detail View -> Edit YAML -> Cancel returns to overview not detail page

### Expected Behavior

PolicyServers -> Detail View -> Edit YAML -> Cancel returns to detail page

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
This has also been fixed by b91ef38a14cfb4203e93c1abe86e782cb60c38fa

https://user-images.githubusercontent.com/40806497/164268675-f5b65340-0aa5-400a-9097-ca24c80612bc.mp4
