### ISSUE TITLE
Remove dots at bottom of tab box

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the policy server config, in the verification tab, it shows 3 dots at the bottom below the input.

### Expected Behavior

There should not be any extra text. 

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
This was due to `insecureSources` being empty and the `ArrayListGroup` component adding a default value.

![verification-tab](https://user-images.githubusercontent.com/40806497/164272777-cad02682-6048-468f-a666-412dd0861c28.png)
