### ISSUE TITLE
Capitalise first letter of all messages

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ClusterAdmissionPolicies, among others, show messages in which the first letter is lowercase.

### Expected Behavior

The first letter should be capitalized

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
@kwwii Can you give some examples of where the messages are located? The only ones that come to mind are the messages returned from Jaeger in the Tracing tabs, am I missing any?

**Comment by kwwii** [comment]
The only place I noticed this was the red text that appears in the jaeger tracing messeges. Not sure if it happens anywhere else, but I haven't seen it

**Comment by jordojordo** [comment]
https://github.com/rancher/dashboard/commit/d1a89fe1f24fcfcbac20f4870958def1c9756d1a

---
The response message that is returned from Jaeger will now be capitalized.

![messages](https://user-images.githubusercontent.com/40806497/165555807-8d36d9c5-3599-45dd-8098-a921fc8351f3.png)
