### ISSUE TITLE
Service account name shoud be a picker input on Policy Server Create/Config page

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is currently only an input

### Expected Behavior

Offer the user list of possible names to choose from

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
You can now choose from a list of Service Account Names depending on the selected namespace for the policy server. This will only appear if the user has the ability to see these names as well.

https://user-images.githubusercontent.com/40806497/169142375-0cf68611-26bb-402f-8923-e5618bdcced5.mp4
