### ISSUE TITLE
Move Replicas to new line

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Move the replicas to a new line in the create/config page of Policy Servers

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
![policy-server-config](https://user-images.githubusercontent.com/40806497/168631782-fe98b420-e708-4df1-8f9c-19a865df2ddd.png)
