### ISSUE TITLE
Policy Server Create/Config page error handling

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Improve the error handling when creating a new config.

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
Error handling now works correctly when editing/creating policy servers or cluster/admission policies.

_Policy Server_
https://user-images.githubusercontent.com/40806497/169314784-c4e35d6a-2edf-44f1-96ab-be3b68276c6e.mp4
_Admission Policy_
https://user-images.githubusercontent.com/40806497/169314804-f73382d0-350b-4b18-aff2-cb3a1153f15e.mp4
