### ISSUE TITLE
Show related policies tab even if none exist

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The Policy Server detail page should always show the related policies tab

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jordojordo** [comment]
![no-related](https://user-images.githubusercontent.com/40806497/168659099-2e6ccc71-652c-4c10-b1dd-b25b4308015a.png)
