### ISSUE TITLE
Show fewer tooltips and more description texts in the admission policies creation UI

### ISSUE THREAD

**Issue by kwwii** [kubewarden/ui#85]

**Comment by jordojordo** [comment]
This was completed with #193 

For example:
_Host Namespaces PSP_
![settings1](https://user-images.githubusercontent.com/40806497/212357712-c6230edb-0773-40ca-8835-f9be749ad392.png)

_Verify Image Signatures_
![settings2](https://user-images.githubusercontent.com/40806497/212357783-7f344188-7409-4fac-80f1-4a669c109cc5.png)

_Sysctl PSP_
![settings3](https://user-images.githubusercontent.com/40806497/212357906-6e3e7c34-9cb3-4772-91cd-57c04f4337c2.png)
